#include <JoltPlugin/JoltPluginPCH.h>

PLASMA_STATICLINK_LIBRARY(JoltPlugin)
{
  if (bReturn)
    return;

  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltActorComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltDynamicActorComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltQueryShapeActorComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltStaticActorComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltTriggerComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltCharacterControllerComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltDefaultCharacterComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltBoneColliderComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRagdollComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRopeComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltSettingsComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltVisColMeshComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_Jolt6DOFConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConeConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltDistanceConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltFixedConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltGrabObjectComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltHingeConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltPointConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSliderConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSwingTwistConstraintComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltMeshResource);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltCustomShapeInfo);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeBoxComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCapsuleComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeConvexHullComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCylinderComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeSphereComponent);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_Startup);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltCollisionFiltering);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltContacts);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltCore);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltDebugRenderer);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltQueries);
  PLASMA_STATICLINK_REFERENCE(JoltPlugin_System_JoltWorldModule);
}
