#include <JoltPlugin/JoltPluginPCH.h>

PL_STATICLINK_LIBRARY(JoltPlugin)
{
  if (bReturn)
    return;

  PL_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltActorComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltDynamicActorComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltQueryShapeActorComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltStaticActorComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltTriggerComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltCharacterControllerComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltDefaultCharacterComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltBoneColliderComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRagdollComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRopeComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltSettingsComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltVisColMeshComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_Jolt6DOFConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConeConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltDistanceConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltFixedConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltGrabObjectComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltHingeConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltPointConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSliderConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSwingTwistConstraintComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltMeshResource);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltCustomShapeInfo);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeBoxComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCapsuleComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeConvexHullComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCylinderComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeSphereComponent);
  PL_STATICLINK_REFERENCE(JoltPlugin_Startup);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltCollisionFiltering);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltContacts);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltCore);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltDebugRenderer);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltQueries);
  PL_STATICLINK_REFERENCE(JoltPlugin_System_JoltWorldModule);
}
