#include <Foundation/FoundationPCH.h>

PL_STATICLINK_LIBRARY(Foundation)
{
  if (bReturn)
    return;

  PL_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_FileSystemConfig);
  PL_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_PluginConfig);
  PL_STATICLINK_REFERENCE(Foundation_Communication_Implementation_Message);
  PL_STATICLINK_REFERENCE(Foundation_Communication_Implementation_MessageLoop);
  PL_STATICLINK_REFERENCE(Foundation_Communication_Implementation_RemoteMessage);
  PL_STATICLINK_REFERENCE(Foundation_Configuration_Implementation_CVar);
  PL_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_DefaultImplementations_Implementation_ZeroInitializer);
  PL_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_Implementation_ProcessingStreamProcessor);
  PL_STATICLINK_REFERENCE(Foundation_IO_Archive_Implementation_DataDirTypeArchive);
  PL_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_DataDirTypeFolder);
  PL_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_FileSystem);
  PL_STATICLINK_REFERENCE(Foundation_Logging_Implementation_LogEntry);
  PL_STATICLINK_REFERENCE(Foundation_Math_Implementation_Math);
  PL_STATICLINK_REFERENCE(Foundation_Memory_Implementation_FrameAllocator);
  PL_STATICLINK_REFERENCE(Foundation_Profiling_Implementation_Profiling);
  PL_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyAttributes);
  PL_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyPath);
  PL_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_RTTI);
  PL_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_StandardTypes);
  PL_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_AbstractObjectGraph);
  PL_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_GraphVersioning);
  PL_STATICLINK_REFERENCE(Foundation_System_Implementation_StackTracer);
  PL_STATICLINK_REFERENCE(Foundation_Threading_Implementation_TaskSystem);
  PL_STATICLINK_REFERENCE(Foundation_Threading_Implementation_ThreadUtils);
  PL_STATICLINK_REFERENCE(Foundation_Time_Implementation_Clock);
  PL_STATICLINK_REFERENCE(Foundation_Time_Implementation_Time);
  PL_STATICLINK_REFERENCE(Foundation_Time_Implementation_Timestamp);
  PL_STATICLINK_REFERENCE(Foundation_Types_Implementation_VarianceTypes);
  PL_STATICLINK_REFERENCE(Foundation_Types_Implementation_VariantTypeRegistry);
}
