#include <RendererFoundation/RendererFoundationPCH.h>

PLASMA_STATICLINK_LIBRARY(RendererFoundation)
{
  if (bReturn)
    return;

  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Basics);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_CommandEncoder);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_CommandEncoderState);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_ComputeCommandEncoder);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_CommandEncoder_Implementation_RenderCommandEncoder);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_Device);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_DeviceFactory);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_Pass);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_SwapChain);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Device_Implementation_SharedTextureSwapChain);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Profiling_Implementation_Profiling);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Buffer);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ProxyTexture);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Query);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_RenderTargetSetup);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_RenderTargetView);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ResourceFormats);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_ResourceView);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_Texture);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Resources_Implementation_UnorderedAccessView);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_Shader);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_ShaderByteCode);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_Shader_Implementation_VertexDeclaration);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_State_Implementation_State);
  PLASMA_STATICLINK_REFERENCE(RendererFoundation_State_Implementation_RendererReflection);
}
