#pragma once

// Configure the DLL Import/Export Define
#if PLASMA_ENABLED(PLASMA_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_RMLUIPLUGIN_LIB
#    define PLASMA_RMLUIPLUGIN_DLL PLASMA_DECL_EXPORT
#  else
#    define PLASMA_RMLUIPLUGIN_DLL PLASMA_DECL_IMPORT
#  endif
#else
#  define PLASMA_RMLUIPLUGIN_DLL
#endif

#ifndef RMLUI_USE_CUSTOM_RTTI
#  define RMLUI_USE_CUSTOM_RTTI
#endif
