#include <RendererVulkan/RendererVulkanPCH.h>

PL_STATICLINK_LIBRARY(RendererVulkan)
{
  if (bReturn)
    return;

  PL_STATICLINK_REFERENCE(RendererVulkan_Context_Implementation_ContextVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_DeviceVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_SwapChainVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_BufferVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_FenceVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_QueryVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_RenderTargetViewVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_ResourceViewVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_TextureVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_SharedTextureVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_UnorderedAccessViewVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_ShaderVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_VertexDeclarationVulkan);
  PL_STATICLINK_REFERENCE(RendererVulkan_State_Implementation_StateVulkan);
}
