#include <Foundation/FoundationPCH.h>

#include <Foundation/Math/Transform.h>
#include <Foundation/Reflection/Reflection.h>
#include <Foundation/Strings/HashedString.h>

// clang-format off
PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plEnumBase, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plBitflagsBase, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_DYNAMIC_REFLECTED_TYPE(plReflectedClass, 1, plRTTINoAllocator)
PLASMA_END_DYNAMIC_REFLECTED_TYPE;

// *********************************************
// ***** Standard POD Types for Properties *****

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(bool, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(float, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(double, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plInt8, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUInt8, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plInt16, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUInt16, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plInt32, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUInt32, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plInt64, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUInt64, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plConstCharPtr, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plTime, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Nanoseconds, In, "Nanoseconds")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Microseconds, In, "Microseconds")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Milliseconds, In, "Milliseconds")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Seconds, In, "Seconds")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Minutes, In, "Minutes")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Hours, In, "Hours")->AddFlags(plPropertyFlags::Const),
    PLASMA_SCRIPT_FUNCTION_PROPERTY(Zero)->AddFlags(plPropertyFlags::Const),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plColor, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("r", r),
    PLASMA_MEMBER_PROPERTY("g", g),
    PLASMA_MEMBER_PROPERTY("b", b),
    PLASMA_MEMBER_PROPERTY("a", a),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(float, float, float),
    PLASMA_CONSTRUCTOR_PROPERTY(float, float, float, float),
    PLASMA_CONSTRUCTOR_PROPERTY(plColorLinearUB),
    PLASMA_CONSTRUCTOR_PROPERTY(plColorGammaUB),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plColorBaseUB, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("r", r),
    PLASMA_MEMBER_PROPERTY("g", g),
    PLASMA_MEMBER_PROPERTY("b", b),
    PLASMA_MEMBER_PROPERTY("a", a),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8, plUInt8),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plColorGammaUB, plColorBaseUB, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8, plUInt8),
    PLASMA_CONSTRUCTOR_PROPERTY(const plColor&),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plColorLinearUB, plColorBaseUB, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt8, plUInt8, plUInt8, plUInt8),
    PLASMA_CONSTRUCTOR_PROPERTY(const plColor&),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec2, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(float),
    PLASMA_CONSTRUCTOR_PROPERTY(float, float),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec3, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(float),
    PLASMA_CONSTRUCTOR_PROPERTY(float, float, float),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec4, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
    PLASMA_MEMBER_PROPERTY("w", w),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(float),
    PLASMA_CONSTRUCTOR_PROPERTY(float, float, float, float),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec2I32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32, plInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec3I32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32, plInt32, plInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec4I32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
    PLASMA_MEMBER_PROPERTY("w", w),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plInt32, plInt32, plInt32, plInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec2U32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32, plUInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec3U32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32, plUInt32, plUInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVec4U32, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("x", x),
    PLASMA_MEMBER_PROPERTY("y", y),
    PLASMA_MEMBER_PROPERTY("z", z),
    PLASMA_MEMBER_PROPERTY("w", w),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32),
    PLASMA_CONSTRUCTOR_PROPERTY(plUInt32, plUInt32, plUInt32, plUInt32),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plQuat, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("v", v),
    PLASMA_MEMBER_PROPERTY("w", w),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(float, float, float, float),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plMat3, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plMat4, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plTransform, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("Position", m_vPosition),
    PLASMA_MEMBER_PROPERTY("Rotation", m_qRotation),
    PLASMA_MEMBER_PROPERTY("Scale", m_vScale),
  }
  PLASMA_END_PROPERTIES;
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_CONSTRUCTOR_PROPERTY(plVec3, plQuat),
    PLASMA_CONSTRUCTOR_PROPERTY(plVec3, plQuat, plVec3),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_ENUM(plBasisAxis, 1)
PLASMA_ENUM_CONSTANT(plBasisAxis::PositiveX),
PLASMA_ENUM_CONSTANT(plBasisAxis::PositiveY),
PLASMA_ENUM_CONSTANT(plBasisAxis::PositiveZ),
PLASMA_ENUM_CONSTANT(plBasisAxis::NegativeX),
PLASMA_ENUM_CONSTANT(plBasisAxis::NegativeY),
PLASMA_ENUM_CONSTANT(plBasisAxis::NegativeZ),
PLASMA_END_STATIC_REFLECTED_ENUM;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUuid, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVariant, plNoBase, 3, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVariantArray, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plVariantDictionary, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plString, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plUntrackedString, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plStringView, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plDataBuffer, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plHashedString, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plTempHashedString, plNoBase, 1, plRTTINoAllocator)
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plAngle, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_FUNCTIONS
  {
    PLASMA_FUNCTION_PROPERTY(Degree),
    PLASMA_FUNCTION_PROPERTY(Radian),
  }
  PLASMA_END_FUNCTIONS;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plFloatInterval, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("Start", m_StartValue),
    PLASMA_MEMBER_PROPERTY("End", m_EndValue),
  }
  PLASMA_END_PROPERTIES;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

PLASMA_BEGIN_STATIC_REFLECTED_TYPE(plIntInterval, plNoBase, 1, plRTTINoAllocator)
{
  PLASMA_BEGIN_PROPERTIES
  {
    PLASMA_MEMBER_PROPERTY("Start", m_StartValue),
    PLASMA_MEMBER_PROPERTY("End", m_EndValue),
  }
  PLASMA_END_PROPERTIES;
}
PLASMA_END_STATIC_REFLECTED_TYPE;

// **********************************************************************
// ***** Various RTTI infos that can't be put next to their classes *****

PLASMA_BEGIN_STATIC_REFLECTED_BITFLAGS(plTypeFlags, 1)
PLASMA_BITFLAGS_CONSTANTS(plTypeFlags::StandardType, plTypeFlags::IsEnum, plTypeFlags::Bitflags, plTypeFlags::Class, plTypeFlags::Abstract, plTypeFlags::Phantom, plTypeFlags::Minimal)
PLASMA_END_STATIC_REFLECTED_BITFLAGS;

PLASMA_BEGIN_STATIC_REFLECTED_BITFLAGS(plPropertyFlags, 1)
PLASMA_BITFLAGS_CONSTANTS(plPropertyFlags::StandardType, plPropertyFlags::IsEnum, plPropertyFlags::Bitflags, plPropertyFlags::Class)
PLASMA_BITFLAGS_CONSTANTS(plPropertyFlags::Const, plPropertyFlags::Reference, plPropertyFlags::Pointer)
PLASMA_BITFLAGS_CONSTANTS(plPropertyFlags::PointerOwner, plPropertyFlags::ReadOnly, plPropertyFlags::Hidden, plPropertyFlags::Phantom)
PLASMA_END_STATIC_REFLECTED_BITFLAGS;

PLASMA_BEGIN_STATIC_REFLECTED_ENUM(plFunctionType, 1)
PLASMA_ENUM_CONSTANTS(plFunctionType::Member, plFunctionType::StaticMember, plFunctionType::Constructor)
PLASMA_END_STATIC_REFLECTED_ENUM;

PLASMA_BEGIN_STATIC_REFLECTED_ENUM(plVariantType, 1)
PLASMA_ENUM_CONSTANTS(plVariantType::Invalid, plVariantType::Bool, plVariantType::Int8, plVariantType::UInt8, plVariantType::Int16, plVariantType::UInt16)
PLASMA_ENUM_CONSTANTS(plVariantType::Int32, plVariantType::UInt32, plVariantType::Int64, plVariantType::UInt64, plVariantType::Float, plVariantType::Double)
PLASMA_ENUM_CONSTANTS(plVariantType::Color, plVariantType::Vector2, plVariantType::Vector3, plVariantType::Vector4)
PLASMA_ENUM_CONSTANTS(plVariantType::Vector2I, plVariantType::Vector3I, plVariantType::Vector4I, plVariantType::Vector2U, plVariantType::Vector3U, plVariantType::Vector4U)
PLASMA_ENUM_CONSTANTS(plVariantType::Quaternion, plVariantType::Matrix3, plVariantType::Matrix4, plVariantType::Transform)
PLASMA_ENUM_CONSTANTS(plVariantType::String, plVariantType::StringView, plVariantType::DataBuffer, plVariantType::Time, plVariantType::Uuid, plVariantType::Angle, plVariantType::ColorGamma)
PLASMA_ENUM_CONSTANTS(plVariantType::HashedString, plVariantType::TempHashedString)
PLASMA_ENUM_CONSTANTS(plVariantType::VariantArray, plVariantType::VariantDictionary, plVariantType::TypedPointer, plVariantType::TypedObject)
PLASMA_END_STATIC_REFLECTED_ENUM;

PLASMA_BEGIN_STATIC_REFLECTED_ENUM(plPropertyCategory, 1)
PLASMA_ENUM_CONSTANTS(plPropertyCategory::Constant, plPropertyCategory::Member, plPropertyCategory::Function, plPropertyCategory::Array, plPropertyCategory::Set, plPropertyCategory::Map)
PLASMA_END_STATIC_REFLECTED_ENUM;
// clang-format on

PLASMA_STATICLINK_FILE(Foundation, Foundation_Reflection_Implementation_StandardTypes);
