#include <AudioSystemPlugin/AudioSystemPluginPCH.h>

#include <AudioSystemPlugin/AudioSystemPluginDLL.h>

#include <Foundation/Configuration/Plugin.h>
#include <Foundation/Strings/TranslationLookup.h>

PLASMA_STATICLINK_LIBRARY(AudioSystemPlugin)
{
  if (bReturn)
    return;

  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_AudioSystemStartup);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_AudioSystem);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_AudioSystemAllocator);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_AudioSystemData);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_AudioSystemMessages);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_ATL_AudioTranslationLayer);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioBoxEnvironmentComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioAnimationComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioListenerComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioProxyComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioRtpcComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioSphereEnvironmentComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioSwitchStateComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioSystemComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Components_AudioTriggerComponent);
  PLASMA_STATICLINK_REFERENCE(AudioSystemPlugin_Implementation_Core_AudioWorldModule);
}
