#pragma once

// Configure the DLL Import/Export Define
#if PLASMA_ENABLED(PLASMA_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_PROCGENPLUGIN_LIB
#    define PLASMA_PROCGENPLUGIN_DLL PLASMA_DECL_EXPORT
#  else
#    define PLASMA_PROCGENPLUGIN_DLL PLASMA_DECL_IMPORT
#  endif
#else
#  define PLASMA_PROCGENPLUGIN_DLL
#endif
