#include <RendererDX11/RendererDX11PCH.h>

PL_STATICLINK_LIBRARY(RendererDX11)
{
  if (bReturn)
    return;

  PL_STATICLINK_REFERENCE(RendererDX11_Context_Implementation_ContextDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Device_Implementation_DeviceDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Device_Implementation_SwapChainDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_BufferDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_FenceDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_QueryDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_RenderTargetViewDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_ResourceViewDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_TextureDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_SharedTextureDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Resources_Implementation_UnorderedAccessViewDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Shader_Implementation_ShaderDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_Shader_Implementation_VertexDeclarationDX11);
  PL_STATICLINK_REFERENCE(RendererDX11_State_Implementation_StateDX11);
}
